apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  name: #<mpiJobName>
  # namespace: By default will be assigned the same namespace as notebook.
  labels:
    notebook-name: #<notebookName>
spec:
  #slotsPerWorker: Tensorflow example sets this attribute, but Pat's example template doesn't.
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        metadata:
          labels:
            data.statcan.gc.ca/inject-blob-volumes: 'true' # Access blob storage.
            sidecar.istio.io/inject: "false" # Init container conflicts with istio.
        spec:
          containers:
          - image: k8scc01covidacr.azurecr.io/ompp-run-ubuntu:0f80cf47bb5d6f6e025990e511b72be614bbcf7c
            # There must be a better way than just hardcoding these image names in here, right?
            name: #<mpiJobName>-launcher
            command:
            - mpirun
            #<mpirunOption>
            - /bin/bash
            - -c
            #<bashArguments>
            resources:
              limits:
                cpu: '2'
                memory: 2Gi
              requests:
                cpu: 250m
                memory: 250Mi

    Worker:
      replicas: #<numberOfReplicas>
      template:
        metadata:
          labels:
            data.statcan.gc.ca/inject-blob-volumes: 'true' # Access blob storage.
            sidecar.istio.io/inject: "false" # Init container conflicts with istio.
        spec:
          containers:
          - image: k8scc01covidacr.azurecr.io/ompp-run-ubuntu:0f80cf47bb5d6f6e025990e511b72be614bbcf7c
            # Same as above, I don't think this should be hardcoded in like this.
            name: #<mpiJobName>-worker
            resources:
                limits:
                  cpu: '2'
                  memory: 2Gi
                requests:
                  cpu: '2'
                  memory: 1Gi

            # In the tensorflow example there are volume and volume mount definitions for the worker pods.
            # I don't think this is necessary if the container images used in the worker pod definitions
            # have COPY directives that populate the ephemeral filesystem with the required files.
