apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: #<mpiJobName>
  # namespace: By default will be assigned the same namespace as notebook.
  labels:
    notebook-name: #<notebookName>
spec:
  # Experimenting with a hard-coded value of 2 that should fit our standard 2-core cluster nodes.
  slotsPerWorker: 2
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        metadata:
          labels:
            data.statcan.gc.ca/inject-blob-volumes: 'true' # Access blob storage.
            sidecar.istio.io/inject: "false" # Init container conflicts with istio.
        spec:
          containers:
          - image: k8scc01covidacr.azurecr.io/ompp-run-ubuntu:c6a1cb9eb74ec1c8cac268a66313d0db9fad651b
            name: #<mpiJobName>-launcher
            command:
            - mpirun
            - --display-map
            #<mpirunOption>
            - /bin/bash
            - -c
            #<bashArguments>
            resources:
              limits:
                cpu: '2'
                memory: 2Gi
              requests:
                cpu: 250m
                memory: 250Mi

    Worker:
      replicas: #<numberOfReplicas>
      template:
        metadata:
          labels:
            data.statcan.gc.ca/inject-blob-volumes: 'true' # Access blob storage.
            sidecar.istio.io/inject: "false" # Init container conflicts with istio.
        spec:
          containers:
          - image: k8scc01covidacr.azurecr.io/ompp-run-ubuntu:c6a1cb9eb74ec1c8cac268a66313d0db9fad651b
            name: #<mpiJobName>-worker
            resources:
                limits:
                  cpu: '5'
                  memory: 5Gi
                requests:
                  cpu: '4'
                  memory: 4Gi
            volumeMounts:
            - mountPath: /home/jovyan/mpi-test
              name: mpi-test-nfs
          volumes:
          - name: mpi-test-nfs
            persistentVolumeClaim:
              claimName: mpi-test-nfs

            # In the tensorflow example there are volume and volume mount definitions for the worker pods.
            # I don't think this is necessary if the container images used in the worker pod definitions
            # have COPY directives that populate the ephemeral filesystem with the required files.
