apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: mpi-job-runner
    namespace: aaw-team
    # labels:
rules:
- apiGroups: 
  - kubeflow.org
  resources:
  - mpijobs
  verbs:
  - get
  - list
  - create
  - watch

